### PR TITLE
override general output settings with specific example ones

### LINKED ISSUE #29: The output settings should probably be set for each test
```
examples:
- name: '...'
  postconditions:
    equal:
      '22FF': 'FFFF'
- name: '...'
  postconditions:
    equal:
      '22FE': 'FFFF'
output:
  flags: false
  records: true
  special_records: false
  memory:
    from: '0050'
    to: '0060'
```
Right now `output:` is aligned with `examples:`, but they should probably (and ideally) be set for each test, according to the repo's readme. However, aligning it like
```
examples:
- name: '...'
  postconditions:
    equal:
      '22FF': 'FFFF'
  output:
    flags: false
    records: true
    special_records: false
    memory:
      from: '0050'
      to: '0060'
- name: '...'
  postconditions:
    equal:
      '22FE': 'FFFF'
  output:
    flags: false
    records: true
    special_records: false
    memory:
      from: '0050'
      to: '0060'
```
does not work (default output settings are used).

### PR DESCRIPTION
**Pull request by julian-berbel**
Fixes #29.

### CODE REVIEW

**Comment by julian-berbel** [comment]
adding some tests tomorrow o/

**Comment by julian-berbel** [comment]
Also, this allows giving general output settings for all given examples as it is working right now, and then giving other example specific settings that override those. Here's an example test YAML:

```
examples:
- name: 'R4 is 22FF'
  preconditions:
      R4: '22FF'
  postconditions:
    equal:
      R4: '22FF'
  output:
    memory:
      from: '0100'
      to: '0150'
- name: 'memory position EEEF is 22FF'
  preconditions:
      EEEF: '22FF'
  postconditions:
    equal:
      EEEF: '22FF'
output:
  flags: true
  records: false
  special_records: true
  memory:
    from: '0000'
    to: '0010'
```

For this YAML, `flags`, `records` and `special_records`  would be set to the same for both examples and `memory` would be set to (0100..0150) for the first example and (0000..0010) for the second.

**Review by flbulgarelli — CHANGES_REQUESTED** [review]
Could we add a test please?

**Review by fedescarpa — APPROVED** [review]
LGTM

**Pull request merged**
